### ISSUE TITLE
Peer to Peer Code Review

### ISSUE THREAD

**Issue by sawmon71293** [bronnie313/Portfolio#9]
https://github.com/bronnie313/Portfolio/blob/77b9a9b9310a56bff4667aa04c3855ac0c9a63f1/index.html#L52

-  You've done quite a good job. But if you can change the resolution of the pictures, your design will be flawless.

**Comment by supreeti** [comment]
You did great job but i suggest that in about section the social icons needs some fixing on the left side as per figma design.

**Comment by sumon766** [comment]
Good job Ronnie, it can be seen that you have put your hard work into this project. Though there are some minor fixes that can make your site great. Firstly add a link to the site logo or title and also add a link to the menu items so that they work like links and possibly they navigate to the specific sections of the page. 
![Document](https://user-images.githubusercontent.com/22003499/216261662-13a4e7a6-4e10-4c21-9c57-eea0bbb1c3c1.png)


Also please reduce the spacing in the second post (Multi-Post Stories) between the title and list items, so that it will look good. Follow the screenshot.
![Document (1)](https://user-images.githubusercontent.com/22003499/216261862-3be96546-a9c9-4e44-b014-bfa3bb033d71.png)
